<Project>
    <PropertyGroup>
        <NBGV_ThisAssemblyIncludesPackageVersion>true</NBGV_ThisAssemblyIncludesPackageVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning"
                          Condition="'$(MSBuildProjectName)' != 'RasHub.Contracts'"
                          Version="3.10.94"
                          PrivateAssets="all"/>
    </ItemGroup>
</Project>
