<Project>
    <PropertyGroup>
        <NBGV_ThisAssemblyIncludesPackageVersion>true</NBGV_ThisAssemblyIncludesPackageVersion>
        <NuGetAudit>true</NuGetAudit>
        <NuGetAuditMode>all</NuGetAuditMode>
        <WarningsAsErrors>$(WarningsAsErrors);NU1903;NU1904</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning"
                          Condition="'$(MSBuildProjectName)' != 'RasHub.Contracts'"
                          Version="3.10.94"
                          PrivateAssets="all"/>
    </ItemGroup>
</Project>
